title : The Robot Professor
description: 'Even robots need professors!'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins:
- jekyll-gist
- jekyll-paginate
permalink: /:year/:month/:title.html
